version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /root/data_disk/graylog/mongodb/data:/data/db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - graylog-net

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - /root/data_disk/graylog/opensearch/data:/usr/share/opensearch/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx1g
      - plugins.security.ssl.http.enabled=false
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=4_IGHfQnJ86xU49xB@55ctJscpM4%2DV
    networks:
      - graylog-net

  graylog:
    image: graylog/graylog:6.0.3
    container_name: graylog
    logging:
      driver: gelf
      options:
        gelf-address: "udp:10.100.1.23:514"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - GRAYLOG_PASSWORD_SECRET=HacKThC2o9GR4GBxNk1MRIxGmpYJJf7TvBYiX9P3lFQTm84kxrKvuoL5SHasqJRG8ZpUVbQ5GH1FXLdIHFJJpn6Cw1obX8vy
      - GRAYLOG_HTTP_EXTERNAL_URI=http://0.0.0.0:9000/
      - GRAYLOG_WEB_ENDPOINT_URI=http://0.0.0.0:9000/api
      - GRAYLOG_ROOT_PASSWORD_SHA2=1a9cb401248451103c8cc3830fc9e19e99d7d14874a7d851d8bfe961818ab0c0
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
      - GRAYLOG_ROOT_TIMEZONE=Asia/Shanghai
    ports:
      - "9000:9000"
      - "1514:1514"
      - "1514:1514/udp"
      - "2514:2514"
      - "2514:2514/udp"
      - "3514:3514"
      - "3514:3514/udp"
      - "4514:4514"
      - "4514:4514/udp"
      - "5514:5514"
      - "5514:5514/udp"
      - "12201:12201"
      - "12201:12201/udp"
    networks:
      - graylog-net
    depends_on:
      - mongodb
      - opensearch
  
networks:
  graylog-net:
    driver: bridge
