services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql
    restart: always
    ports:
      - 10051:10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/zabbix/zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - /data/zabbix/zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - /data/zabbix/zbx_env/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
      - /data/zabbix/zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - /data/zabbix/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - /data/zabbix/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - /data/zabbix/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - /data/zabbix/zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - snmptraps:/var/lib/zabbix/snmptraps:rw
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    env_file:
      - /data/zabbix/zbx_env/.env_db_mysql
      - /data/zabbix/zbx_env/.env_srv
    depends_on:
      - mysql-server
    networks:
      zbx_net:
        aliases:
          - zabbix-server
          - zabbix-server-mysql
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 64999
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    labels:
      com.zabbix.description: Zabbix server with MySQL database support
      com.zabbix.company: Zabbix LLC
      com.zabbix.component: zabbix-server
      com.zabbix.dbtype: mysql
      com.zabbix.os: Alpine
  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/zabbix/zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
      - /data/zabbix/zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
      #- /usr/share/fonts/adobe-source-han-sans-cn/SourceHanSansCN-Normal.otf:/usr/share/zabbix/assets/fonts/DejaVuSans.ttf
    env_file:
      - /data/zabbix/zbx_env/.env_db_mysql
      - /data/zabbix/zbx_env/.env_web
    depends_on:
      - mysql-server
      - zabbix-server
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost/
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      zbx_net:
        aliases:
          - zabbix-web-nginx-mysql
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    labels:
      com.zabbix.description: Zabbix frontend on Nginx web-server with MySQL database support
      com.zabbix.company: Zabbix LLC
      com.zabbix.component: zabbix-frontend
      com.zabbix.webserver: nginx
      com.zabbix.dbtype: mysql
      com.zabbix.os: Alpine
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway
    restart: always
    ports:
      - 10052:10052
    env_file:
      - /data/zabbix/zbx_env/.env_java
    networks:
      zbx_net:
        aliases:
          - zabbix-java-gateway
    stop_grace_period: 5s
    labels:
      com.zabbix.description: Zabbix Java Gateway
      com.zabbix.company: Zabbix LLC
      com.zabbix.component: java-gateway
      com.zabbix.os: Alpine
  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps
    restart: always
    profiles:
      - full
      - all
    ports:
      - 162:1162/udp
    volumes:
      - snmptraps:/var/lib/zabbix/snmptraps:rw
    networks:
      zbx_net:
        aliases:
          - zabbix-snmptraps
    stop_grace_period: 5s
    labels:
      com.zabbix.description: Zabbix snmptraps
      com.zabbix.company: Zabbix LLC
      com.zabbix.component: snmptraps
      com.zabbix.os: Alpine
  mysql-server:
    image: mysql:8.0-oracle
    restart: always
    security_opt:
      - seccomp:unconfined
    command:
      - mysqld
      - --skip-mysqlx
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      # Only during upgrade from versions prior 6.4 and new installations (schema deployment)
      #- --log_bin_trust_function_creators=1
      - --log_timestamps=SYSTEM
      - --binlog_expire_logs_seconds=3600
      - --innodb_buffer_pool_size=2G
      - --max_connections=500
      - --wait_timeout=1200
      - --interactive_timeout=1200
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/zabbix/zbx_env/var/lib/mysql:/var/lib/mysql:rw
      - /data/backup/mysql:/data/backup/mysql:rw
    env_file:
      - /data/zabbix/zbx_env/.env_db_mysql
    stop_grace_period: 1m
    networks:
      zbx_net:
        aliases:
          - mysql-server
          - zabbix-database
          - mysql-database
  db_data_mysql:
    image: busybox
    volumes:
      - /data/zabbix/zbx_env/var/lib/mysql:/var/lib/mysql:rw
networks:
  zbx_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
volumes:
  snmptraps: null
